# 服务器配置
server:
  port: 8083
  servlet:
    context-path: /api
    encoding:
      charset: UTF-8
      enabled: true
      force: true

# HTTP编码配置
http:
  encoding:
    charset: UTF-8
    enabled: true
    force: true
    force-request: true
    force-response: true

# SQL脚本初始化配置 - 禁用自动执行
sql:
  init:
    mode: never  # 改为never，不再每次启动都执行SQL脚本
    # schema-locations: classpath:sql/schema.sql
    # data-locations: classpath:sql/data.sql
    # encoding: utf-8
    # continue-on-error: false

# JPA配置（用于自动创建表）
jpa:
  hibernate:
    ddl-auto: validate  # 改为validate，只验证表结构不创建
  database-platform: org.hibernate.dialect.MySQL8Dialect
  show-sql: false  # 关闭SQL日志以减少噪音

# MyBatis Plus 配置
mybatis-plus:
  configuration:
    # 开启驼峰命名转换
    map-underscore-to-camel-case: true
    # 显示SQL
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      # 逻辑删除字段
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
      # 主键策略
      id-type: auto
  # mapper映射文件位置
  mapper-locations: classpath:mapper/*.xml

# 日志配置
logging:
  level:
    com.employee.management: debug
    org.springframework.web: debug
    com.alibaba.nacos: debug  # 启用Nacos详细日志
    com.alibaba.nacos.client: debug  # 启用Nacos客户端详细日志

# Actuator配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,nacos-config
  endpoint:
    health:
      show-details: always
      show-components: always
  health:
    nacos-config:
      enabled: true

# Spring配置
spring:
  application:
    name: employee-management
  # 激活的环境配置 - 从环境变量读取
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:default}
  # 配置导入 - 从Nacos获取配置
  config:
    import: optional:nacos:application-${spring.profiles.active:default}.yml
  # Nacos配置
  cloud:
    nacos:
      config:
        server-addr: ${NACOS_SERVER_ADDR:114.55.135.154:8848}
        file-extension: yml
        group: DEFAULT_GROUP
        namespace: ""
        username: ${NACOS_USERNAME:nacos}
        password: ${NACOS_PASSWORD:nacos}
        refresh-enabled: true
        import-check:
          enabled: false
        remote-first: false
      discovery:
        server-addr: ${NACOS_SERVER_ADDR:114.55.135.154:8848}
        group: DEFAULT_GROUP
        namespace: ""
        username: ${NACOS_USERNAME:nacos}
        password: ${NACOS_PASSWORD:nacos}